## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.size()

torch.Size([2, 2])

In [12]:
MATRIX[1].ndim

1

In [13]:
MATRIX[1].size()

torch.Size([2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[7,8],
                       [9,10]],
                      [[11,12],
                       [13,14]]])
TENSOR

tensor([[[ 7,  8],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.size()

torch.Size([2, 2, 2])

In [17]:
TENSOR[0]

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
TENSOR[0,0]

tensor([7, 8])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/2.8/generated/torch.rand.html

In [25]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2511, 0.7605, 0.9265, 0.0613],
        [0.2472, 0.7404, 0.1585, 0.2913],
        [0.8951, 0.6173, 0.4553, 0.8380]])

In [26]:
random_tensor.ndim

2

In [29]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [30]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [38]:
# Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# Creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes are one of the three big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [52]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor? (e.g. float32 or float64)
                               device="cuda", # where is the tensor on? (e.g. cpu or cuda)
                               requires_grad=False) # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [55]:
float_32_tensor.dtype

torch.float32

In [54]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [56]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [59]:
int_32_tensor = torch.tensor([2, 6, 3],
                             dtype=torch.int32,
                             device="cuda",
                             requires_grad=False)
int_32_tensor

tensor([2, 6, 3], device='cuda:0', dtype=torch.int32)

In [60]:
int_32_tensor * float_32_tensor

tensor([ 6., 36., 27.], device='cuda:0')

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get data type, use `tensor.dtype`
2. Tensors not right shape - to get shape, use `tensor.shape`
3. Tensors not on the right device - to get device, use `tensor.device`

In [71]:
# Create a tensor
some_tensor = torch.rand(3,4, dtype=torch.float16, device="cuda")
some_tensor

tensor([[0.9648, 0.7969, 0.0481, 0.0878],
        [0.3572, 0.6191, 0.3926, 0.3364],
        [0.0490, 0.0029, 0.5156, 0.2101]], device='cuda:0',
       dtype=torch.float16)

In [72]:
# Find out details about some tensor
print(some_tensor)
print()
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9648, 0.7969, 0.0481, 0.0878],
        [0.3572, 0.6191, 0.3926, 0.3364],
        [0.0490, 0.0029, 0.5156, 0.2101]], device='cuda:0',
       dtype=torch.float16)

Data type of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [73]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [74]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [76]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])