## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.size()

torch.Size([2, 2])

In [12]:
MATRIX[1].ndim

1

In [13]:
MATRIX[1].size()

torch.Size([2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[7,8],
                       [9,10]],
                      [[11,12],
                       [13,14]]])
TENSOR

tensor([[[ 7,  8],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.size()

torch.Size([2, 2, 2])

In [17]:
TENSOR[0]

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
TENSOR[0,0]

tensor([7, 8])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/2.8/generated/torch.rand.html

In [19]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0210, 0.5725, 0.7628, 0.5586],
        [0.7831, 0.6823, 0.3622, 0.5718],
        [0.2341, 0.2313, 0.4214, 0.7284]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [26]:
# Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes are one of the three big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor? (e.g. float32 or float64)
                               device="cuda", # where is the tensor on? (e.g. cpu or cuda)
                               requires_grad=False) # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [32]:
int_32_tensor = torch.tensor([2, 6, 3],
                             dtype=torch.int32,
                             device="cuda",
                             requires_grad=False)
int_32_tensor

tensor([2, 6, 3], device='cuda:0', dtype=torch.int32)

In [33]:
int_32_tensor * float_32_tensor

tensor([ 6., 36., 27.], device='cuda:0')

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get data type, use `tensor.dtype`
2. Tensors not right shape - to get shape, use `tensor.shape`
3. Tensors not on the right device - to get device, use `tensor.device`

In [34]:
# Create a tensor
some_tensor = torch.rand(3,4, dtype=torch.float16, device="cuda")
some_tensor

tensor([[0.5566, 0.0947, 0.4924, 0.8174],
        [0.4221, 0.7002, 0.2483, 0.5576],
        [0.5908, 0.7769, 0.8755, 0.8672]], device='cuda:0',
       dtype=torch.float16)

In [35]:
# Find out details about some tensor
print(some_tensor)
print()
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5566, 0.0947, 0.4924, 0.8174],
        [0.4221, 0.7002, 0.2483, 0.5576],
        [0.5908, 0.7769, 0.8755, 0.8672]], device='cuda:0',
       dtype=torch.float16)

Data type of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [39]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match:
    * `(3, 2) @ (3, 2)` won't work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimentions**:
    * `(2, 3) @ (3, 2)` will result in a matrix of shape `(2, 2)`
    * `(3, 2) @ (2, 3)` will result in a matrix of shape `(3, 3)`

In [40]:
# Create two tensors
tensor_1 = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
tensor_2 = torch.tensor([[7, 8],
                         [10, 11],
                         [12, 13]])
tensor_1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
tensor_2

tensor([[ 7,  8],
        [10, 11],
        [12, 13]])

In [42]:
# Element wise multiplication
print(tensor_1, '*', tensor_1)
print(f"Equals: {tensor_1 * tensor_1}")

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]])
Equals: tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [43]:
# Matrix multiplication
torch.matmul(tensor_1, tensor_2)

tensor([[ 63,  69],
        [150, 165]])

In [44]:
%%time
torch.matmul(tensor_1, tensor_2)

CPU times: total: 0 ns
Wall time: 46 μs


tensor([[ 63,  69],
        [150, 165]])

### One of the most common errors in deep learning: shape errors

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axis or dimensions of a given tensor.

In [45]:
tensor_1, tensor_1.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [46]:
tensor_1.T, tensor_1.T.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

In [47]:
torch.mm(tensor_1, tensor_1.T) # torch.mm() is the same as torch.matmul()

tensor([[14, 32],
        [32, 77]])